### PR TITLE
Fix UnicodeEncodeError caused by non encoded msg body.

### PR DESCRIPTION
**Pull request by Ousret**
Hi,

Thank for this awesome project @lavr !

I propose this PR in order to fix an unexpected issue. All characters outside of the ASCII range (in body msg) is going to trigger a exception.

```
  File "/home/x/.local/lib/python3.7/site-packages/emails-0.5.15-py3.7.egg/emails/backend/smtp/backend.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "/home/x/.local/lib/python3.7/site-packages/emails-0.5.15-py3.7.egg/emails/backend/smtp/backend.py", line 103, in _send
    return client.sendmail(**kwargs)
  File "/home/x/.local/lib/python3.7/site-packages/emails-0.5.15-py3.7.egg/emails/backend/smtp/client.py", line 105, in sendmail
    (code, resp) = self.data(msg)
  File "/usr/x/lib/python3.7/smtplib.py", line 563, in data
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1163: ordinal not in range(128)
```

This change will encode body in specified charset (in object Message).

### CODE REVIEW

**Comment by Ousret** [comment]
ping @lavr 😀

**Comment by lavr** [comment]
@Ousret please show code snippet that generates UnicodeEncodeError exception.
I believe we should reproduce bug in tests before fix it.

**Comment by Ousret** [comment]
Hi @lavr ,

I will add one asap.

**Comment by lavr** [comment]
Still no example body to reproduce error.
Commit https://github.com/lavr/python-emails/commit/0dba9d67921664e30deb29fad83e9fe9c3190574 may fix this

**Pull request closed without merging**
